Feature: Check The Flow Of Vajro Web Application
Scenario: User Launches The Browser
Given User Select The Categories Required
When Product Category
And Average Revenue
And Push Notification And Mobile Engagement
And Traffic Limit
And Usage From Mobile Devices
And Repeated Buy
And Repeated Purchase From The Store
And Impluse Purchase
And Followers On Social Media
And Store Name
Then User Submits The Mail_Id To Receive Emails 

Scenario: Getting Mobile App
When User Clicks The Button-Get Your Mobile App Now 

Scenario: User Clicks On Shopify.com And Creates A New Shopify Account
When User Clicks On Shopify.com
And User Clicks On Login Button
Then User Clicks Get Started

Scenario: User Enters Details To Create A New Shopify Account
When User Enters The Email
And User Enters FirstName
And User Enters LastName
And User Enters Password
And User Enters ConfirmNewPassword
Then User Clicks On Create Shopify ID